/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rname */

#ifndef _Included_rname
#define _Included_rname
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rname
 * Method:    rJarName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rname_rJarName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
