/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rrname */

#ifndef _Included_rrname
#define _Included_rrname
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rrname
 * Method:    rrJarName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rrname_rrJarName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
